/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hoteldula.gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import hoteldula.connection.MySQL;
import hoteldula.panel.UserInformation;

import java.sql.ResultSet;
import hoteldula.util.AppIconUtil;
import hoteldula.validation.Validator;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author dulan
 */
public class LogInScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LogInScreen() {
        initComponents();
        init();
    }
    
    public void init(){
        AppIconUtil.applyIcon(this);
        ImageIcon bgI = new ImageIcon(getClass().getResource("/hoteldula/img/logo.jpg"));
        Image bgSI = bgI.getImage().getScaledInstance(161, 152, Image.SCALE_SMOOTH);
        ImageIcon bgRI = new ImageIcon(bgSI);
        loginlogo.setIcon(bgRI);
        
        FlatSVGIcon svgIcon = new FlatSVGIcon("hoteldula/img/icon.svg", 60, 60);
        loginIcon.setIcon(svgIcon);
        
          SignInBtn.setIcon(new FlatSVGIcon("hoteldula/img/SignIn.svg", 20, 20));
          SignInBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          CreateNewAccountBtn.setIcon(new FlatSVGIcon("hoteldula/img/Registration.svg", 20, 20));
          CreateNewAccountBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginlogo = new javax.swing.JLabel();
        loginIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PasswordInput = new javax.swing.JPasswordField();
        SignInBtn = new javax.swing.JButton();
        CreateNewAccountBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Script MT Bold", 1, 36)); // NOI18N
        jLabel1.setText("Welcome...");

        jLabel2.setFont(new java.awt.Font("Modern No. 20", 1, 20)); // NOI18N
        jLabel2.setText("Sign In");

        jLabel3.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel3.setText("Email");

        jLabel4.setFont(new java.awt.Font("Lucida Fax", 1, 14)); // NOI18N
        jLabel4.setText("Password");

        SignInBtn.setBackground(new java.awt.Color(0, 153, 255));
        SignInBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SignInBtn.setForeground(new java.awt.Color(0, 0, 0));
        SignInBtn.setText("Sign In");
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });

        CreateNewAccountBtn.setBackground(new java.awt.Color(255, 51, 51));
        CreateNewAccountBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CreateNewAccountBtn.setForeground(new java.awt.Color(255, 255, 255));
        CreateNewAccountBtn.setText("Registration");
        CreateNewAccountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateNewAccountBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EmailInput)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(PasswordInput)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SignInBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CreateNewAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(loginIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(loginlogo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(PasswordInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(SignInBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CreateNewAccountBtn)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreateNewAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateNewAccountBtnActionPerformed
                 new SignUpScreen().setVisible(true);
                 
    }//GEN-LAST:event_CreateNewAccountBtnActionPerformed

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
                String email = EmailInput.getText().trim();
                String password = String.valueOf(PasswordInput.getPassword());
               
                 
                 if (!Validator.isEmailValid(email)) {
                   return;
                }
                 if (!Validator.isPasswordValid(password)) {
                   return;
                }
                 
                 try {
                    ResultSet rs = MySQL.executeSearch("SELECT * FROM `user` "
                    + "WHERE `user`.`email` = '" + email + "' &&"
                    + " `user`.`password` = '" + password + "'");
                    
                    if (rs.next()) {
                if (rs.getInt("status_id") == 1) { // Active
                    JOptionPane.showMessageDialog(this,"Login Successfully","Success Message",JOptionPane.INFORMATION_MESSAGE);
                    
                    String FirstName = rs.getString("first_name");
                    String LastName  = rs.getString("last_name");
                    String FullName  = FirstName + " " + LastName;
                    
                    User user = new User(
                           rs.getInt("id"),
                           rs.getString("first_name"),
                           rs.getString("last_name"),
                           rs.getString("address"),
                           rs.getString("email"),
                           rs.getString("password"),
                           rs.getString("mobile"),
                           rs.getString("gender")

                    );
                    
                    
                    HomeScreen home = new HomeScreen(FullName, user);
                    
                    home.setVisible(true);
                    this.dispose(); 
                    
                   
                    
                } else {
                    JOptionPane.showMessageDialog(this,
                            "OOPS!... Your account is Inactive. Please contact admin","Error Message",
                            JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this,
                        " OOPS!... Please Check Your Email Address And Password \n"
                                + "                                          OR         \n"
                       +" This email dosen't have a account. Please First Create New Account \n.","Error Message ",
                        JOptionPane.ERROR_MESSAGE);
            }
                } catch (Exception e) {
                    e.printStackTrace();
                }
                         
    }//GEN-LAST:event_SignInBtnActionPerformed

    
      
    /**
     * @param args the command line arguments
     */
     
      private static LogInScreen loginScreen;
    public static void main(String args[]) {
        FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LogInScreen dialog = new LogInScreen();
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateNewAccountBtn;
    private javax.swing.JTextField EmailInput;
    private javax.swing.JPasswordField PasswordInput;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginIcon;
    private javax.swing.JLabel loginlogo;
    // End of variables declaration//GEN-END:variables
}
