/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package hoteldula.dialog;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import hoteldula.connection.MySQL;
import hoteldula.panel.InvoicePanel;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dulan
 */
public class AddNewInformation extends javax.swing.JDialog {

    /**
     * Creates new form AddNewInformation
     */
    private static InvoicePanel invoicePanel;
      Map<String, Integer> unitMap = new HashMap<>();
      Map<String, Integer> statusMap1 = new HashMap<>();
    
    public AddNewInformation(java.awt.Frame parent, boolean modal, InvoicePanel panel) {
        super(parent, modal);
        this.invoicePanel = panel;
        
        initComponents();
        init();
        loadRoomTypeDetails();
    }
    
    public void init(){
          AddInformationSubmitBtn.setIcon(new FlatSVGIcon("hoteldula/img/Submit.svg", 15, 15));
          AddInformationSubmitBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          AddInformationLoadDataBtn.setIcon(new FlatSVGIcon("hoteldula/img/LoadData.svg", 20, 20));
          AddInformationLoadDataBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          RemoveInfoBtn.setIcon(new FlatSVGIcon("hoteldula/img/Remove.svg", 20, 20));
          RemoveInfoBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
    
    }
    
    public void loadRoomTypeDetails(){
           try {
              ResultSet rs = MySQL.executeSearch("SELECT * FROM `unit`" );
            
            Vector <String> v = new Vector<>();  
            v.add("Select");
            while (rs.next()) {
                int id = rs.getInt("id");
                String name = rs.getString("name");
                 v.add(name);
                 
                 unitMap.put(name, id);
                
            }
            DefaultComboBoxModel<String> dcm = new DefaultComboBoxModel(v);
            InfoCategoryIDComboBox.setModel(dcm);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InfoIDInput = new javax.swing.JTextField();
        InfoDescriptionInput = new javax.swing.JTextField();
        InfoUnitPriceInput = new javax.swing.JTextField();
        InfoCategoryIDComboBox = new javax.swing.JComboBox<>();
        InfoItemQuantityInput = new javax.swing.JTextField();
        InfoAmountInput = new javax.swing.JTextField();
        AddInformationSubmitBtn = new javax.swing.JButton();
        AddInformationLoadDataBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        InfoNoInput = new javax.swing.JTextField();
        RemoveInfoBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 16)); // NOI18N
        jLabel1.setText("Add Information");

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel2.setText("Info ID");

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel3.setText("Description");

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel4.setText("Category ID");

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel5.setText("Unit Price (Rs)");

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel6.setText("Quantity");

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel7.setText("Amount (Rs)");

        InfoIDInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoIDInputActionPerformed(evt);
            }
        });

        InfoDescriptionInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoDescriptionInputActionPerformed(evt);
            }
        });

        InfoUnitPriceInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoUnitPriceInputActionPerformed(evt);
            }
        });

        InfoCategoryIDComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        AddInformationSubmitBtn.setBackground(new java.awt.Color(0, 153, 255));
        AddInformationSubmitBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddInformationSubmitBtn.setText("Submit");
        AddInformationSubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInformationSubmitBtnActionPerformed(evt);
            }
        });

        AddInformationLoadDataBtn.setBackground(new java.awt.Color(0, 204, 0));
        AddInformationLoadDataBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddInformationLoadDataBtn.setForeground(new java.awt.Color(255, 255, 255));
        AddInformationLoadDataBtn.setText("Load Data");
        AddInformationLoadDataBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInformationLoadDataBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel8.setText("No");

        RemoveInfoBtn.setBackground(new java.awt.Color(255, 51, 0));
        RemoveInfoBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        RemoveInfoBtn.setForeground(new java.awt.Color(0, 0, 0));
        RemoveInfoBtn.setText("Remove");
        RemoveInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveInfoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(InfoIDInput)
                            .addComponent(InfoDescriptionInput)
                            .addComponent(InfoUnitPriceInput)
                            .addComponent(InfoCategoryIDComboBox, 0, 190, Short.MAX_VALUE)
                            .addComponent(InfoItemQuantityInput)
                            .addComponent(InfoAmountInput)
                            .addComponent(InfoNoInput))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RemoveInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddInformationLoadDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddInformationSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(InfoIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(InfoNoInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(InfoDescriptionInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(InfoCategoryIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(InfoUnitPriceInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(InfoItemQuantityInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(InfoAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddInformationSubmitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddInformationLoadDataBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RemoveInfoBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InfoIDInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoIDInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoIDInputActionPerformed

    private void InfoUnitPriceInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoUnitPriceInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoUnitPriceInputActionPerformed

    private void AddInformationLoadDataBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInformationLoadDataBtnActionPerformed
                       try {
                         
                           ResultSet rs = MySQL.executeSearch("SELECT * FROM `invoice_table` INNER JOIN `unit` ON `invoice_table`.`unit_id` = `unit`.`id` ORDER BY `no` ASC; " );
            
                          JTable table = invoicePanel.getInvoiceInfoTable();
                          DefaultTableModel dtm = (DefaultTableModel)table.getModel();
                          dtm.setRowCount(0);
            
                         while (rs.next()) {                
                            Vector<String> v = new Vector<>();
                
                                v.add(rs.getString("no"));
                                v.add(rs.getString("description"));
                                v.add(rs.getString("name"));
                                v.add(rs.getString("unit_price"));
                                v.add(rs.getString("quantity"));
                                v.add(rs.getString("amount"));
                
               
                            dtm.addRow(v);
                         }
            
                       } catch (java.sql.SQLException e) {
                           
                  }
    }//GEN-LAST:event_AddInformationLoadDataBtnActionPerformed

    private void AddInformationSubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInformationSubmitBtnActionPerformed
              
              String no           = InfoIDInput.getText();
              String description  = InfoDescriptionInput.getText();
              
              String unit_name      = (String) InfoCategoryIDComboBox.getSelectedItem();
              int unit_id           = unitMap.get(unit_name);
              
              String unit_price   = InfoUnitPriceInput.getText();
              String quantity     = InfoItemQuantityInput.getText();
              String amount       = InfoAmountInput.getText();
              
              
              try {
              MySQL.executeIUD("INSERT INTO `invoice_table`(`no`,`description`,`unit_id`,`unit_price`,`quantity`,`amount`) VALUES"
                       + "('"+no+"','"+description+"','"+unit_id+"','"+unit_price+"','"+quantity+"','"+amount+"')");
               
                JOptionPane.showMessageDialog(this,"Informations Add Successfully !!!","Success Message",JOptionPane.INFORMATION_MESSAGE);
                
        } catch (Exception e) {
             e.printStackTrace();
        }
    }//GEN-LAST:event_AddInformationSubmitBtnActionPerformed

    private void RemoveInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveInfoBtnActionPerformed
            try {
                         int choise = JOptionPane.showConfirmDialog(null, "Do you want to Delete Details", "Confirmation", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                                  switch (choise) {
                                      case JOptionPane.YES_OPTION:
                                               MySQL.executeIUD("DELETE FROM `invoice_table`");
                                              
                                               JTable table = invoicePanel.getInvoiceInfoTable();
                                               DefaultTableModel dtm = (DefaultTableModel)table.getModel();
                                              dtm.setRowCount(0);
                                         break;
                                      case JOptionPane.NO_OPTION:
                                         break;
                                      default:
                                          
                                    }
                          
                           
                     
        } catch (Exception e) {
             e.printStackTrace();
        }
           
    }//GEN-LAST:event_RemoveInfoBtnActionPerformed

    private void InfoDescriptionInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoDescriptionInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfoDescriptionInputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         FlatIntelliJLaf.setup();
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddNewInformation dialog = new AddNewInformation(new javax.swing.JFrame(), true, invoicePanel);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInformationLoadDataBtn;
    private javax.swing.JButton AddInformationSubmitBtn;
    private javax.swing.JTextField InfoAmountInput;
    private javax.swing.JComboBox<String> InfoCategoryIDComboBox;
    private javax.swing.JTextField InfoDescriptionInput;
    private javax.swing.JTextField InfoIDInput;
    private javax.swing.JTextField InfoItemQuantityInput;
    private javax.swing.JTextField InfoNoInput;
    private javax.swing.JTextField InfoUnitPriceInput;
    private javax.swing.JButton RemoveInfoBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
