/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hoteldula.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import hoteldula.connection.MySQL;
import hoteldula.dialog.AddNewPayment;
import hoteldula.gui.HomeScreen;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dulan
 */
public class FinancialPanel extends javax.swing.JPanel {

    /**
     * Creates new form FinancialReportPanel
     */
    private HomeScreen homeScreen;
    
    public FinancialPanel() {
        initComponents();
        init();
        loadDataToTable();
    }
    
    public JTable getFinancialInfoTable(){
      return financialInfoTable;
   }
     
    public void init(){
          AddNewPaymentDetailsBtn.setIcon(new FlatSVGIcon("hoteldula/img/AddNew.svg", 20, 20));
          AddNewPaymentDetailsBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          GenerateReportBtn.setIcon(new FlatSVGIcon("hoteldula/img/Report.svg", 20, 20));
          GenerateReportBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");

    
    }
    
    public void loadDataToTable(){
              try {
                    ResultSet rs = MySQL.executeSearch("SELECT * FROM `financial` INNER JOIN `reserver` ON `financial`.`reserver_id` = `reserver`.`reserver_id` "
                    + " INNER JOIN `status` ON `financial`.`status_id` = `status`.`status_id` ORDER BY `id` ASC;" );
            
            DefaultTableModel dtm = (DefaultTableModel)financialInfoTable.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                Vector<String> v = new Vector<>();
                v.add(rs.getString("invoice_id"));
                v.add(rs.getString("reserver_id"));
                v.add(rs.getString("issue_date"));
                v.add(rs.getString("total_amount"));
                v.add(rs.getString("discount"));
                v.add(rs.getString("final_amount"));
                v.add(rs.getString("payment_method"));
                v.add(rs.getString("status_name"));
                
                dtm.addRow(v);
            }
            
        } catch (java.sql.SQLException e) {
              e.printStackTrace();
        }

    


    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        financialInfoTable = new javax.swing.JTable();
        AddNewPaymentDetailsBtn = new javax.swing.JButton();
        GenerateReportBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Financial Informations");

        financialInfoTable.setBackground(new java.awt.Color(235, 231, 231));
        financialInfoTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        financialInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Invoice ID", "Reserver ID", "Issue Date", "Total Amount (Rs)", "Discount (Rs)", "Final Amount (Rs)", "Payment Method", "Status"
            }
        ));
        financialInfoTable.setGridColor(new java.awt.Color(51, 51, 51));
        financialInfoTable.setShowGrid(true);
        jScrollPane2.setViewportView(financialInfoTable);
        if (financialInfoTable.getColumnModel().getColumnCount() > 0) {
            financialInfoTable.getColumnModel().getColumn(0).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(1).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(2).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(3).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(4).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(5).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(6).setResizable(false);
            financialInfoTable.getColumnModel().getColumn(7).setResizable(false);
        }

        AddNewPaymentDetailsBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddNewPaymentDetailsBtn.setText("Add New Payment");
        AddNewPaymentDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewPaymentDetailsBtnActionPerformed(evt);
            }
        });

        GenerateReportBtn.setBackground(new java.awt.Color(255, 204, 0));
        GenerateReportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenerateReportBtn.setText("Generate Report");
        GenerateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GenerateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AddNewPaymentDetailsBtn))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AddNewPaymentDetailsBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerateReportBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewPaymentDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewPaymentDetailsBtnActionPerformed
        AddNewPayment addNewPaymentDialog = new AddNewPayment(homeScreen, true,this);
        addNewPaymentDialog.setLocationRelativeTo(this);
        addNewPaymentDialog.setVisible(true);
    }//GEN-LAST:event_AddNewPaymentDetailsBtnActionPerformed

    private void GenerateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportBtnActionPerformed
           try {
            InputStream filePath = getClass().getClassLoader()
                                    .getResourceAsStream("hoteldula/report/Financial_Information.jasper");
            HashMap<String, Object> parameters = new HashMap<>();
            
            JRTableModelDataSource  jRTableModelDataSource = new JRTableModelDataSource(financialInfoTable.getModel());
            JasperPrint fillReport = JasperFillManager.fillReport(filePath, parameters, jRTableModelDataSource);
            JasperViewer viewer = new JasperViewer(fillReport, false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);
            
            JasperExportManager.exportReportToPdfFile(fillReport, "report.pdf");
            
        } catch (JRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GenerateReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewPaymentDetailsBtn;
    private javax.swing.JButton GenerateReportBtn;
    private javax.swing.JTable financialInfoTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    
}
