/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hoteldula.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import hoteldula.connection.MySQL;
import hoteldula.dialog.AddNewInformation;
import hoteldula.gui.HomeScreen;

import java.io.InputStream;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dulan
 */
public class InvoicePanel extends javax.swing.JPanel {

    /**
     * Creates new form InvoicePanel1
     */
    private HomeScreen homeScreen;
    
    public InvoicePanel() {
        initComponents();
        init();
        loadInfoDataToTable();
    }
    
    public JTable getInvoiceInfoTable(){
         return InfoTable;
    }
    
      
    public void init(){
          AddInformationBtn.setIcon(new FlatSVGIcon("hoteldula/img/AddNew.svg", 20, 20));
          AddInformationBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          GenerateInvoiceBtn.setIcon(new FlatSVGIcon("hoteldula/img/Report.svg", 20, 20));
          GenerateInvoiceBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
    }
    
    public void loadInfoDataToTable(){
         try {
            ResultSet rs = MySQL.executeSearch("SELECT * FROM `invoice_table` INNER JOIN `unit` ON `invoice_table`.`unit_id` = `unit`.`id` ORDER BY `no` ASC;" );
            
            DefaultTableModel dtm = (DefaultTableModel)InfoTable.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                Vector<String> v = new Vector<>();
                
                v.add(rs.getString("no"));
                v.add(rs.getString("description"));
                v.add(rs.getString("name"));
                v.add(rs.getString("unit_price"));
                v.add(rs.getString("quantity"));
                v.add(rs.getString("amount"));
                
               
                dtm.addRow(v);
            }
            
        } catch (java.sql.SQLException e) {
        }



   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        InvoiceIDInput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        IssueDateInput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ReserverNameInput = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ReserverEmailInput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ReserverAddressInput = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PaymentMethodComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        CheckInInput = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CheckOutInput = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        InfoTable = new javax.swing.JTable();
        GenerateInvoiceBtn = new javax.swing.JButton();
        AddInformationBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TotalAmountInput = new javax.swing.JTextField();
        DiscountInput = new javax.swing.JTextField();
        FinalAmountInput = new javax.swing.JTextField();
        ReserverIDInput = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Invoice");

        jLabel2.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel2.setText("Invoice ID");

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel3.setText("Issue Date");

        jLabel4.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel4.setText("Reserver ID");

        jLabel5.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel5.setText("Reserver Name");

        jLabel6.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel6.setText("Reserver Email");

        jLabel7.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel7.setText("Reserver Address");

        ReserverAddressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserverAddressInputActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel8.setText("Payment Method");

        PaymentMethodComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Select Method -- ", "By Cash", "Credit Card or Debit Card", "Bank Transfer" }));
        PaymentMethodComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentMethodComboBoxActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel9.setText("Check In Date");

        jLabel10.setFont(new java.awt.Font("Perpetua", 1, 14)); // NOI18N
        jLabel10.setText("Check Out Date");

        InfoTable.setBackground(new java.awt.Color(235, 231, 231));
        InfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Description", "Unit", "Unit Price (Rs)", "Unit Quantity", "Amount (Rs)"
            }
        ));
        InfoTable.setGridColor(new java.awt.Color(51, 51, 51));
        InfoTable.setShowGrid(true);
        jScrollPane1.setViewportView(InfoTable);
        if (InfoTable.getColumnModel().getColumnCount() > 0) {
            InfoTable.getColumnModel().getColumn(0).setResizable(false);
            InfoTable.getColumnModel().getColumn(1).setResizable(false);
            InfoTable.getColumnModel().getColumn(2).setResizable(false);
            InfoTable.getColumnModel().getColumn(3).setResizable(false);
            InfoTable.getColumnModel().getColumn(4).setResizable(false);
            InfoTable.getColumnModel().getColumn(5).setResizable(false);
        }

        GenerateInvoiceBtn.setBackground(new java.awt.Color(255, 0, 51));
        GenerateInvoiceBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenerateInvoiceBtn.setForeground(new java.awt.Color(255, 255, 255));
        GenerateInvoiceBtn.setText("Generate Invoice");
        GenerateInvoiceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateInvoiceBtnActionPerformed(evt);
            }
        });

        AddInformationBtn.setBackground(new java.awt.Color(0, 153, 255));
        AddInformationBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddInformationBtn.setText("Add Information");
        AddInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddInformationBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Total Amount");

        jLabel12.setText("Discount");

        jLabel13.setText("Final Amount");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DiscountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FinalAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CheckOutInput, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 659, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(InvoiceIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IssueDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PaymentMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ReserverNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ReserverEmailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ReserverAddressInput, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(ReserverIDInput)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AddInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(GenerateInvoiceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckInInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReserverIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReserverNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvoiceIDInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReserverEmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ReserverAddressInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IssueDateInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PaymentMethodComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckInInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckOutInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiscountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FinalAmountInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenerateInvoiceBtn)
                    .addComponent(AddInformationBtn))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ReserverAddressInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserverAddressInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserverAddressInputActionPerformed

    private void AddInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddInformationBtnActionPerformed
        AddNewInformation addNewInformationDialog = new AddNewInformation(homeScreen, true, this);
        addNewInformationDialog.setLocationRelativeTo(this);
        addNewInformationDialog.setVisible(true);
    }//GEN-LAST:event_AddInformationBtnActionPerformed

    private void PaymentMethodComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentMethodComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PaymentMethodComboBoxActionPerformed

    private void GenerateInvoiceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateInvoiceBtnActionPerformed
               String invoiceId = InvoiceIDInput.getText().trim();
               String issueDate = IssueDateInput.getText().trim();
               
               String paymentMethod = PaymentMethodComboBox.getSelectedItem().toString();
               
               String reserverID = ReserverIDInput.getText().trim();
               String reserverName = ReserverNameInput.getText().trim();
               String reserverEmail = ReserverEmailInput.getText().trim();
               String reserverAddress = ReserverAddressInput.getText().trim();
               String checkIn   = CheckInInput.getText().trim();
               String checkOut  = CheckOutInput.getText().trim();
               
              
               
               String totalAmount = TotalAmountInput.getText().trim();
               String discount    = DiscountInput.getText().trim();
               String finalAmount = FinalAmountInput.getText().trim();
               
               
               try {
                          InputStream filePath = getClass().getClassLoader()
                                    .getResourceAsStream("hoteldula/report/Invoice.jasper");
                        
                             
                          
                               HashMap<String, Object> parameters = new HashMap<>(); 
                                    parameters.put("INVOICE_ID", invoiceId); 
                                    parameters.put("ISSUE_DATE", issueDate);
                  
                                    parameters.put("PAYMENT_METHOD", paymentMethod);
                  
                                    parameters.put("RESERVER_ID", reserverID);
                                    parameters.put("RESERVER_NAME", reserverName);
                                    parameters.put("RESERVER_EMAIL", reserverEmail);
                                    parameters.put("RESERVER_ADDRESS", reserverAddress);
                                    parameters.put("CHECK_IN", checkIn);
                                    parameters.put("CHECK_OUT",checkOut);
                                    
                                 
                                    parameters.put("TOTAL_AMOUNT", totalAmount);
                                    parameters.put("DISCOUNT", discount);
                                    parameters.put("FINAL_AMOUNT", finalAmount);
                              
                                      JRTableModelDataSource  jRTableModelDataSource = new JRTableModelDataSource(InfoTable.getModel());
                                     JasperPrint fillReport = JasperFillManager.fillReport(filePath, parameters, jRTableModelDataSource);
                              
                                       JasperViewer viewer = new JasperViewer(fillReport, false);
                                        viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                                        viewer.setVisible(true);
                                     
                                     JasperExportManager.exportReportToPdfFile(fillReport, "report.pdf");
                  
                   } catch (Exception e) {
                        e.printStackTrace();
                   }
               
                  
    }//GEN-LAST:event_GenerateInvoiceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddInformationBtn;
    private javax.swing.JTextField CheckInInput;
    private javax.swing.JTextField CheckOutInput;
    private javax.swing.JTextField DiscountInput;
    private javax.swing.JTextField FinalAmountInput;
    private javax.swing.JButton GenerateInvoiceBtn;
    private javax.swing.JTable InfoTable;
    private javax.swing.JTextField InvoiceIDInput;
    private javax.swing.JTextField IssueDateInput;
    private javax.swing.JComboBox<String> PaymentMethodComboBox;
    private javax.swing.JTextField ReserverAddressInput;
    private javax.swing.JTextField ReserverEmailInput;
    private javax.swing.JTextField ReserverIDInput;
    private javax.swing.JTextField ReserverNameInput;
    private javax.swing.JTextField TotalAmountInput;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
