 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package hoteldula.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import hoteldula.connection.MySQL;
import hoteldula.dialog.AddNewReserver;
import hoteldula.gui.HomeScreen;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dulan
 */

public class ReservationPanel extends javax.swing.JPanel {
         
     private HomeScreen homeScreen;
    /**
     * Creates new form ReservationPanel
     */
    public ReservationPanel() {
        initComponents();
        init();
        loadDataToTable();
    
    }
   public JTable getReserversInfoTable(){
      return reservationInfoTable;
   }
           
    public void init(){
          addNewReserverBtn.setIcon(new FlatSVGIcon("hoteldula/img/AddNew.svg", 20, 20));
          addNewReserverBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          GenerateReportBtn.setIcon(new FlatSVGIcon("hoteldula/img/Report.svg", 20, 20));
          GenerateReportBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          
        
    }
    
     public void loadDataToTable(){
               try {
                    ResultSet rs = MySQL.executeSearch("SELECT * FROM `reserver` INNER JOIN `room` ON `reserver`.`room_id` = `room`.`room_id` "
                    + " INNER JOIN `room_type` ON `room`.`room_type_id` = `room_type`.`id` ORDER BY `reserver_id` ASC;" );
            
            DefaultTableModel dtm = (DefaultTableModel)reservationInfoTable.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                Vector<String> v = new Vector<>();
                v.add(rs.getString("reserver_id"));
                v.add(rs.getString("first_name") + " " + rs.getString("last_name"));
                v.add(rs.getString("email"));
                v.add(rs.getString("mobile"));
                v.add(rs.getString("address"));
                v.add(rs.getString("member_count"));
                v.add(rs.getString("room_number"));
                v.add(rs.getString("room_type"));
                v.add(rs.getString("check_in"));
                v.add(rs.getString("check_out"));
               
                dtm.addRow(v);
            }
            
        } catch (java.sql.SQLException e) {
        }
     
     
     }
      
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reservationScrollPane = new javax.swing.JScrollPane();
        reservationInfoTable = new javax.swing.JTable();
        addNewReserverBtn = new javax.swing.JButton();
        GenerateReportBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 255, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Reservation Informations");

        reservationInfoTable.setBackground(new java.awt.Color(235, 231, 231));
        reservationInfoTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        reservationInfoTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reserver ID", "Reserver Name", "Reserver Email", "Reserver Mobile", "Reserver Address", "Member Count", "Room Number", "Room type", "Check In", "Check Out"
            }
        ));
        reservationInfoTable.setAlignmentX(1.0F);
        reservationInfoTable.setAlignmentY(1.0F);
        reservationInfoTable.setGridColor(new java.awt.Color(51, 51, 51));
        reservationInfoTable.setRowMargin(5);
        reservationInfoTable.setShowGrid(true);
        reservationInfoTable.getTableHeader().setReorderingAllowed(false);
        reservationScrollPane.setViewportView(reservationInfoTable);
        if (reservationInfoTable.getColumnModel().getColumnCount() > 0) {
            reservationInfoTable.getColumnModel().getColumn(0).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(1).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(2).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(3).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(4).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(5).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(6).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(7).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(8).setResizable(false);
            reservationInfoTable.getColumnModel().getColumn(9).setResizable(false);
        }

        addNewReserverBtn.setBackground(new java.awt.Color(0, 153, 255));
        addNewReserverBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addNewReserverBtn.setText("Add New Reserver");
        addNewReserverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewReserverBtnActionPerformed(evt);
            }
        });

        GenerateReportBtn.setBackground(new java.awt.Color(255, 204, 0));
        GenerateReportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenerateReportBtn.setForeground(new java.awt.Color(0, 0, 0));
        GenerateReportBtn.setText("Generate Report");
        GenerateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addNewReserverBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reservationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(GenerateReportBtn)))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewReserverBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reservationScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerateReportBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addNewReserverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewReserverBtnActionPerformed
        AddNewReserver addNewReserverDialog = new AddNewReserver(homeScreen, true,this);
        addNewReserverDialog.setLocationRelativeTo(this);
        addNewReserverDialog.setVisible(true);
    }//GEN-LAST:event_addNewReserverBtnActionPerformed

    private void GenerateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportBtnActionPerformed
        try {
            InputStream filePath = getClass().getClassLoader()
                                    .getResourceAsStream("hoteldula/report/Reserver's_Information_Table.jasper");
            HashMap<String, Object> parameters = new HashMap<>();
            
            JRTableModelDataSource  jRTableModelDataSource = new JRTableModelDataSource(reservationInfoTable.getModel());
            JasperPrint fillReport = JasperFillManager.fillReport(filePath, parameters, jRTableModelDataSource);
            JasperViewer viewer = new JasperViewer(fillReport, false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);
           
            JasperExportManager.exportReportToPdfFile(fillReport, "report.pdf");
            
        } catch (JRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GenerateReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GenerateReportBtn;
    private javax.swing.JButton addNewReserverBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTable reservationInfoTable;
    private javax.swing.JScrollPane reservationScrollPane;
    // End of variables declaration//GEN-END:variables

   
}
