/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */ 
package hoteldula.panel;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import hoteldula.connection.MySQL;
import hoteldula.dialog.AddNewRoom;
import hoteldula.gui.HomeScreen;
import java.io.InputStream;
import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Vector;
import javax.swing.JTable;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author dulan
 */
public class RoomsPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoomsPanels
     */
    private HomeScreen homeScreen;
    
    public RoomsPanel() {
        initComponents();
        init();
        loadRoomDataToLabel();
    }
    
    public JTable getRoomsInfoTable(){
      return RoomDetailsLoadTable;
   }
    
    public void init(){
          AddNewRoomBtn.setIcon(new FlatSVGIcon("hoteldula/img/AddNew.svg", 20, 20));
          AddNewRoomBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
          
          GenerateReportBtn.setIcon(new FlatSVGIcon("hoteldula/img/Report.svg", 20, 20));
          GenerateReportBtn.putClientProperty(FlatClientProperties.STYLE, "arc:20");
    
    }
     
    public void loadRoomDataToLabel(){
                try {
            ResultSet rs = MySQL.executeSearch("SELECT * FROM `room` INNER JOIN `room_type` ON `room`.`room_type_id` = `room_type`.`id` "
                    + " INNER JOIN `status` ON `room`.`status_id` = `status`.`status_id` ORDER BY `room_id` ASC;" );
            
            DefaultTableModel dtm = (DefaultTableModel)RoomDetailsLoadTable.getModel();
            dtm.setRowCount(0);
            
            while (rs.next()) {                
                Vector<String> v = new Vector<>();
                v.add(rs.getString("room_id"));
                v.add(rs.getString("room_number"));
                v.add(rs.getString("room_type"));
                v.add(rs.getString("status_name"));
                v.add(rs.getString("maximun_count"));
                
               
                dtm.addRow(v);
            }
            
        } catch (java.sql.SQLException e) {
        }
    
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RoomDetailsLoadTable = new javax.swing.JTable();
        AddNewRoomBtn = new javax.swing.JButton();
        GenerateReportBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 102));
        setPreferredSize(new java.awt.Dimension(475, 350));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setText("Rooms' Informations");

        RoomDetailsLoadTable.setBackground(new java.awt.Color(235, 231, 231));
        RoomDetailsLoadTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        RoomDetailsLoadTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room No", "Room Type", "Room Status", "Maximum Count"
            }
        ));
        RoomDetailsLoadTable.setGridColor(new java.awt.Color(51, 51, 51));
        RoomDetailsLoadTable.setShowGrid(true);
        jScrollPane1.setViewportView(RoomDetailsLoadTable);
        if (RoomDetailsLoadTable.getColumnModel().getColumnCount() > 0) {
            RoomDetailsLoadTable.getColumnModel().getColumn(0).setResizable(false);
            RoomDetailsLoadTable.getColumnModel().getColumn(1).setResizable(false);
            RoomDetailsLoadTable.getColumnModel().getColumn(2).setResizable(false);
            RoomDetailsLoadTable.getColumnModel().getColumn(3).setResizable(false);
            RoomDetailsLoadTable.getColumnModel().getColumn(4).setResizable(false);
        }

        AddNewRoomBtn.setBackground(new java.awt.Color(255, 255, 51));
        AddNewRoomBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AddNewRoomBtn.setText("Add New Room");
        AddNewRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNewRoomBtnActionPerformed(evt);
            }
        });

        GenerateReportBtn.setBackground(new java.awt.Color(255, 204, 0));
        GenerateReportBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GenerateReportBtn.setForeground(new java.awt.Color(0, 0, 0));
        GenerateReportBtn.setText("Generate Report");
        GenerateReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateReportBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(77, 77, 77)
                        .addComponent(AddNewRoomBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(GenerateReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddNewRoomBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GenerateReportBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AddNewRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNewRoomBtnActionPerformed
        AddNewRoom addNewRoomDialog = new AddNewRoom(homeScreen, true, this);
        addNewRoomDialog.setLocationRelativeTo(this);
        addNewRoomDialog.setVisible(true);
    }//GEN-LAST:event_AddNewRoomBtnActionPerformed

    private void GenerateReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateReportBtnActionPerformed
           try {
            InputStream filePath = getClass().getClassLoader()
                                    .getResourceAsStream("hoteldula/report/Bed_Room_Infromations.jasper");
            HashMap<String, Object> parameters = new HashMap<>();
            
            JRTableModelDataSource  jRTableModelDataSource = new JRTableModelDataSource(RoomDetailsLoadTable.getModel());
            JasperPrint fillReport = JasperFillManager.fillReport(filePath, parameters, jRTableModelDataSource);
            JasperViewer viewer = new JasperViewer(fillReport, false);
            viewer.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            viewer.setVisible(true);
            
            JasperExportManager.exportReportToPdfFile(fillReport, "report.pdf");
            
        } catch (JRException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GenerateReportBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNewRoomBtn;
    private javax.swing.JButton GenerateReportBtn;
    private javax.swing.JTable RoomDetailsLoadTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
